In [1]:
import os
import pickle
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
from sklearn.metrics import confusion_matrix


In [13]:
results_dir = 'results'  
pickle_files = [f for f in os.listdir(results_dir) if f.endswith('.pkl') or f.endswith('.pickle')]

data = {}
for fname in pickle_files:
    name = fname.split('_')[0]  # Remove file extension for key
    file_path = os.path.join(results_dir, fname)
    with open(file_path, 'rb') as f:
        data[name] = data.get(name, [])
        data[name].append(pickle.load(f))

In [43]:
all_preds = {}
all_true = {}

for name, items in data.items():
    preds_list, true_list = [], []
    #print(name, len(items))
    for item in items:
        #print(item['pred_labels'].shape, item['true_labels'].shape)
        preds_list.append(item['pred_labels'])
        true_list.append(item['true_labels'])

    all_preds[name] = np.concatenate(preds_list)
    all_true[name] = np.concatenate(true_list)
    print(name, all_preds[name].shape, all_true[name].shape)

tiso (120400, 7) (120400, 7)
infinity (10680, 7) (10680, 7)
c14 (14400, 7) (14400, 7)


In [45]:
name = 'tiso'
preds = all_preds[name]
trues = all_true[name]
print(f"Results for {name}:")
n_cols = preds.shape[1] if preds.ndim > 1 else 1
for col in range(n_cols):
    col_preds = preds[:, col] if n_cols > 1 else preds
    col_trues = trues[:, col] if n_cols > 1 else trues
    print(f"  Column {col}:")
    print("    Accuracy:", accuracy_score(col_trues, col_preds))
    print("    Precision:", precision_score(col_trues, col_preds, average='weighted', zero_division=0))
    print("    Recall:", recall_score(col_trues, col_preds, average='weighted', zero_division=0))
    print("    F1 Score:", f1_score(col_trues, col_preds, average='weighted', zero_division=0))
    print(classification_report(col_trues, col_preds, zero_division=0))
    print("    Confusion Matrix:")
    print(confusion_matrix(col_trues, col_preds))

Results for tiso:
  Column 0:
    Accuracy: 0.45421926910299004
    Precision: 1.0
    Recall: 0.45421926910299004
    F1 Score: 0.6246915836607877
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.45      0.62    120400

    accuracy                           0.45    120400
   macro avg       0.50      0.23      0.31    120400
weighted avg       1.00      0.45      0.62    120400

    Confusion Matrix:
[[    0     0]
 [65712 54688]]
  Column 1:
    Accuracy: 0.6442940199335548
    Precision: 1.0
    Recall: 0.6442940199335548
    F1 Score: 0.7836725210003385
              precision    recall  f1-score   support

           0       1.00      0.64      0.78    120400
           1       0.00      0.00      0.00         0

    accuracy                           0.64    120400
   macro avg       0.50      0.32      0.39    120400
weighted avg       1.00      0.64      0.78    120400

    Confusion Mat

/Users/eagle/Documents/eagle-classification/venv_eagle_class/lib/python3.9/site-packages/sklearn/metrics/_classification.py:407: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(


In [47]:
name = 'c14'
preds = all_preds[name]
trues = all_true[name]
print(f"Results for {name}:")
n_cols = preds.shape[1] if preds.ndim > 1 else 1
for col in range(n_cols):
    col_preds = preds[:, col] if n_cols > 1 else preds
    col_trues = trues[:, col] if n_cols > 1 else trues
    print(f"  Column {col}:")
    print("    Accuracy:", accuracy_score(col_trues, col_preds))
    print("    Precision:", precision_score(col_trues, col_preds, average='weighted', zero_division=0))
    print("    Recall:", recall_score(col_trues, col_preds, average='weighted', zero_division=0))
    print("    F1 Score:", f1_score(col_trues, col_preds, average='weighted', zero_division=0))
    print(classification_report(col_trues, col_preds, zero_division=0))
    print("    Confusion Matrix:")
    print(confusion_matrix(col_trues, col_preds))

Results for c14:
  Column 0:
    Accuracy: 0.44479166666666664
    Precision: 1.0
    Recall: 0.44479166666666664
    F1 Score: 0.6157173756308579
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.44      0.62     14400

    accuracy                           0.44     14400
   macro avg       0.50      0.22      0.31     14400
weighted avg       1.00      0.44      0.62     14400

    Confusion Matrix:
[[   0    0]
 [7995 6405]]
  Column 1:
    Accuracy: 0.9025
    Precision: 1.0
    Recall: 0.9025
    F1 Score: 0.9487516425755584
              precision    recall  f1-score   support

           0       1.00      0.90      0.95     14400
           1       0.00      0.00      0.00         0

    accuracy                           0.90     14400
   macro avg       0.50      0.45      0.47     14400
weighted avg       1.00      0.90      0.95     14400

    Confusion Matrix:
[[12996  1404]
 [    0  

/Users/eagle/Documents/eagle-classification/venv_eagle_class/lib/python3.9/site-packages/sklearn/metrics/_classification.py:407: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(
/Users/eagle/Documents/eagle-classification/venv_eagle_class/lib/python3.9/site-packages/sklearn/metrics/_classification.py:407: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(


In [48]:
name = 'infinity'
preds = all_preds[name]
trues = all_true[name]
print(f"Results for {name}:")
n_cols = preds.shape[1] if preds.ndim > 1 else 1
for col in range(n_cols):
    col_preds = preds[:, col] if n_cols > 1 else preds
    col_trues = trues[:, col] if n_cols > 1 else trues
    print(f"  Column {col}:")
    print("    Accuracy:", accuracy_score(col_trues, col_preds))
    print("    Precision:", precision_score(col_trues, col_preds, average='weighted', zero_division=0))
    print("    Recall:", recall_score(col_trues, col_preds, average='weighted', zero_division=0))
    print("    F1 Score:", f1_score(col_trues, col_preds, average='weighted', zero_division=0))
    print(classification_report(col_trues, col_preds, zero_division=0))
    print("    Confusion Matrix:")
    print(confusion_matrix(col_trues, col_preds))

Results for infinity:
  Column 0:
    Accuracy: 0.2147940074906367
    Precision: 1.0
    Recall: 0.2147940074906367
    F1 Score: 0.35363033759827345
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.21      0.35     10680

    accuracy                           0.21     10680
   macro avg       0.50      0.11      0.18     10680
weighted avg       1.00      0.21      0.35     10680

    Confusion Matrix:
[[   0    0]
 [8386 2294]]
  Column 1:
    Accuracy: 0.9652621722846442
    Precision: 1.0
    Recall: 0.9652621722846442
    F1 Score: 0.9823240745152223
              precision    recall  f1-score   support

           0       1.00      0.97      0.98     10680
           1       0.00      0.00      0.00         0

    accuracy                           0.97     10680
   macro avg       0.50      0.48      0.49     10680
weighted avg       1.00      0.97      0.98     10680

    Confusion Matr

In [59]:
for i in range(5000, 5100):
    print(all_preds['tiso'][i, 0], all_true['tiso'][i, 0])

0 1
1 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
1 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
1 1
1 1
0 1
0 1
1 1
0 1
0 1
1 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1


In [60]:
name = 'C14'
for i in range(5000, 5100):
    print(all_preds['tiso'][i, 0], all_true['tiso'][i, 0])

0 1
1 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
1 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
1 1
1 1
0 1
0 1
1 1
0 1
0 1
1 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1
0 1


In [53]:
data['tiso'][0]['true_labels'][0:20]

array([[1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0]], dtype=int32)

In [64]:
all_true['c14'][0:20]

array([[1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0]], dtype=int32)

In [65]:
data['infinity'][0]['true_labels'][0:20]

array([[1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0]], dtype=int32)

In [66]:
fpath = 'results/infinity_1.pkl'
d1 = pickle.load(open(fpath, 'rb'))
d1['true_labels'][0:20]

array([[1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0]], dtype=int32)